# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 691bd829d4e736e169c572ea7bb23ab1d55d6e20842d75d722dc11ac9f241542fec2adc4d6340393670db6df6a2790cf0bdd3f1bcf3ce5430d84b268ec72a975

test:
  secret_key_base: 1134c03698d1fb9f81e63f2570639c3f172fc5cdb4220907387bfad58df9fd3d56e7922dc236853a315b7a3811a45cfd3dc4f6e1dbcd7041ebdce79b84ea9115

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
